services:
  - type: web
    name: strapi
    env: node
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: 12.22.0
      - key: NODE_ENV
        value: production
      - key: ENV('CLOUDINARY_NAME')
        sync: false
      - key: ENV('CLOUDINARY_KEY')
        sync: false
      - key: ENV('CLOUDINARY_SECRET')
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: strapi
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ENV('ADMIN_JWT_SECRET')
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: ENV('API_TOKEN_SALT')
        generateValue: true

databases:
  - name: strapi
    plan: starter
